export enum ELogServiceEvent {
    USER_LOGIN,
    USER_LOGOUT,
    USER_SIGNUP,
    REFRESH_TOKEN,
    SOCKET_OPENED,
    SOCKET_MESSAGE,
    SOCKET_CLOSE,
    ACCOUNT_DETAILS,
    ACCOUNTS_DETAILS,
    ACCOUNT_UPDATE_DETAILS,
    ACCOUNT_UPDATE_OPTIONS,
    CHAT_CREATE,
    CHAT_CHANGE_NAME,
    CHAT_ADD_ADMIN,
    CHAT_REMOVE_ADMIN,
    CHAT_ADD_USER,
    CHAT_REMOVE_USER,
    CHAT_DELETE,
    FRIEND_ADD_USER,
    FRIEND_REMOVE_USER,
    FRIEND_BLOCK_USER,
    FRIEND_UNBLOCK_USER
}

export enum ELogRequestEvent {
    POST,
    GET,
    PUT,
    DELETE,
    PATCH
}

export enum ELogRouteEvent {
    ACCOUNT,
    AUTH,
    SOCKET,
    CHAT,
    FRIEND
}